# tools/filesystem_mcp.py
# MCP Server 1: Filesystem MCP
# Handles all file operations for the university finder
# - Saves recommendation reports
# - Reads student documents  
# - Lists saved files

import os
import json
from datetime import datetime
from langchain_core.tools import tool

# ─────────────────────────────────────────
# FILESYSTEM MCP SERVER CLASS
# ─────────────────────────────────────────

class FilesystemMCPServer:
    """
    MCP Server for filesystem operations.
    
    This server provides tools for:
    1. Saving reports to files
    2. Reading files
    3. Listing saved reports
    4. Deleting files
    
    In a real MCP deployment, this would run as
    a separate server process. For this project,
    we implement it as a Python class with tools
    that follow the MCP pattern.
    """
    
    def __init__(self, base_path: str = "outputs"):
        """
        Args:
            base_path: folder where all files are saved
        """
        self.base_path = base_path
        
        # Create output folders
        os.makedirs(f"{base_path}/reports",   exist_ok=True)
        os.makedirs(f"{base_path}/profiles",  exist_ok=True)
        os.makedirs(f"{base_path}/documents", exist_ok=True)
        
        print("✅ Filesystem MCP Server initialized")
        print(f"   📁 Output folder: {os.path.abspath(base_path)}")
    
    # ─────────────────────────────────────────
    # TOOL 1: SAVE REPORT
    # ─────────────────────────────────────────
    
    def save_report(self, report_content: str, 
                    student_name: str = "student") -> dict:
        """
        Saves a university recommendation report to a file.
        
        Args:
            report_content: the full report text
            student_name: used for filename
        
        Returns:
            dict with success status and file path
        """
        
        # Create filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = student_name.replace(" ", "_").lower()
        filename  = f"{safe_name}_report_{timestamp}.txt"
        filepath  = os.path.join(self.base_path, "reports", filename)
        
        # Build the full report with header
        full_report = f"""
╔══════════════════════════════════════════════════════╗
║       INTERNATIONAL UNIVERSITY FINDER AI             ║
║       Recommendation Report                          ║
╚══════════════════════════════════════════════════════╝

Generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
Student:   {student_name}

{'='*54}

{report_content}

{'='*54}
Generated by: International University Finder AI
Powered by: LangChain + LangGraph + Groq
"""
        
        # Write to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(full_report)
        
        return {
            "success":  True,
            "message":  f"Report saved successfully!",
            "filepath": filepath,
            "filename": filename,
        }
    
    # ─────────────────────────────────────────
    # TOOL 2: SAVE PROFILE
    # ─────────────────────────────────────────
    
    def save_profile(self, profile: dict,
                     student_name: str = "student") -> dict:
        """
        Saves student profile as a formatted text file.
        
        Args:
            profile: student profile dictionary
            student_name: used for filename
        """
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = student_name.replace(" ", "_").lower()
        filename  = f"{safe_name}_profile_{timestamp}.txt"
        filepath  = os.path.join(self.base_path, "profiles", filename)
        
        # Format profile nicely
        profile_text = f"""
╔══════════════════════════════════════════════════════╗
║              STUDENT PROFILE                         ║
╚══════════════════════════════════════════════════════╝

Generated: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}

"""
        # Add each field
        field_labels = {
            "bachelor_degree":    "Bachelor's Degree",
            "university":         "University",
            "gpa":                "GPA",
            "gpa_scale":          "GPA Scale",
            "graduation_year":    "Graduation Year",
            "target_degree":      "Target Degree",
            "target_field":       "Target Field",
            "target_countries":   "Target Countries",
            "budget_tuition_usd": "Tuition Budget (USD)",
            "budget_initial_pkr": "Initial Budget (PKR)",
            "english_test":       "English Test",
            "english_score":      "English Score",
            "english_exemption":  "English Exemption",
            "target_intake":      "Target Intake",
            "career_goal":        "Career Goal",
            "special_notes":      "Notes",
        }
        
        for field, label in field_labels.items():
            value = profile.get(field)
            if value:
                profile_text += f"  {label:25}: {value}\n"
        
        profile_text += f"\n{'='*54}\n"
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(profile_text)
        
        return {
            "success":  True,
            "message":  "Profile saved successfully!",
            "filepath": filepath,
            "filename": filename,
        }
    
    # ─────────────────────────────────────────
    # TOOL 3: LIST SAVED REPORTS
    # ─────────────────────────────────────────
    
    def list_reports(self) -> dict:
        """
        Lists all saved recommendation reports.
        
        Returns:
            dict with list of saved files
        """
        
        reports_path = os.path.join(self.base_path, "reports")
        
        try:
            files = os.listdir(reports_path)
            txt_files = [f for f in files if f.endswith(".txt")]
            
            if not txt_files:
                return {
                    "success": True,
                    "count":   0,
                    "files":   [],
                    "message": "No saved reports yet.",
                }
            
            # Get file details
            file_details = []
            for fname in txt_files:
                fpath = os.path.join(reports_path, fname)
                size  = os.path.getsize(fpath)
                mtime = os.path.getmtime(fpath)
                mtime_str = datetime.fromtimestamp(mtime).strftime(
                    "%Y-%m-%d %H:%M"
                )
                file_details.append({
                    "filename": fname,
                    "size_kb":  round(size / 1024, 1),
                    "saved_at": mtime_str,
                })
            
            return {
                "success": True,
                "count":   len(file_details),
                "files":   file_details,
                "message": f"Found {len(file_details)} saved reports.",
            }
            
        except Exception as e:
            return {
                "success": False,
                "message": f"Error listing files: {e}",
            }
    
    # ─────────────────────────────────────────
    # TOOL 4: READ REPORT
    # ─────────────────────────────────────────
    
    def read_report(self, filename: str) -> dict:
        """
        Reads a saved report file.
        
        Args:
            filename: name of the file to read
        
        Returns:
            dict with file content
        """
        
        filepath = os.path.join(
            self.base_path, "reports", filename
        )
        
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            
            return {
                "success":  True,
                "filename": filename,
                "content":  content,
            }
            
        except FileNotFoundError:
            return {
                "success": False,
                "message": f"File '{filename}' not found.",
            }
        except Exception as e:
            return {
                "success": False,
                "message": f"Error reading file: {e}",
            }
    
    def get_outputs_path(self) -> str:
        """Returns the absolute path to outputs folder."""
        return os.path.abspath(self.base_path)